- alias: 'Lights Sunset Sunrise'
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:30:00'
  - platform: sun
    event: sunrise
    offset: '-00:15:00'
  action:
  - service: shell_command.volet_all
