
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
#    - platform: myEnedis
#      token: MVlwAMwZQPN4458XmieXTv1Fm7PAmRn6VkQCnOtRBsXxRMu1L8KgHu
#      code: 09326917466545
#      heures_creuses: "[['00:00','05:00'], ['21:30', '24:00']]"
#      hc_cout: 0.15
#      hp_cout: 0.15
#      scan_interval: 3600
    - platform: rflink
      automatic_add: true
      
shell_command:
  light_1: bash /config/relay1.sh
  light_2: bash /config/relay2.sh
  light_3: bash /config/relay3.sh
  light_4: bash /config/relay4.sh
  light_5: bash /config/relay5.sh
  light_6: bash /config/relay6.sh
  light_7: bash /config/relay7.sh
  light_8: bash /config/relay8.sh
  light_9: bash /config/relay9.sh
  light_10: bash /config/relay10.sh
  light_11: bash /config/relay11.sh
  light_12: bash /config/relay12.sh
  light_13: bash /config/relay13.sh
  light_14: bash /config/relay14.sh
  light_15: bash /config/relay15.sh
  light_16: bash /config/relay16.sh
  light_7_11: bash /config/relay_7_11.sh
  light_9_10: bash /config/relay_9_10.sh

switch:
  - platform: template
    switches:
      couloir:
        friendly_name: "couloir"
        turn_on:
          service: shell_command.light_6
        turn_off:
          service: shell_command.light_6
      cuisine:
        friendly_name: "cuisine"
        turn_on:
          service: shell_command.light_5
        turn_off:
          service: shell_command.light_5
      salle:
        friendly_name: "Salle à manger"
        turn_on:
          service: shell_command.light_7_11
        turn_off:
          service: shell_command.light_7_11
      salon:
        friendly_name: "Salon"
        turn_on:
          service: shell_command.light_9_10
        turn_off:
          service: shell_command.light_9_10
      cuisine9:
        friendly_name: "Cuisine9"
        turn_on:
          service: shell_command.light_5
        turn_off:
          service: shell_command.light_5
      couloir1:
        friendly_name: "Couloir1"
        turn_on:
          service: shell_command.light_6
        turn_off:
          service: shell_command.light_6
      cuisine3:
        friendly_name: "Cuisine2"
        turn_on:
          service: shell_command.light_7
        turn_off:
          service: shell_command.light_7
      parking1:
        friendly_name: "Parking1"
        turn_on:
          service: shell_command.light_8
        turn_off:
          service: shell_command.light_8
      entree4:
        friendly_name: "Entree4"
        turn_on:
          service: shell_command.light_9
        turn_off:
          service: shell_command.light_9
      salon5:
        friendly_name: "Salon5"
        turn_on:
          service: shell_command.light_10
        turn_off:
          service: shell_command.light_10
      salon4:
        friendly_name: "Salon4"
        turn_on:
          service: shell_command.light_11
        turn_off:
          service: shell_command.light_11
      terrasse1:
        friendly_name: "Terrasse1"
        turn_on:
          service: shell_command.light_12
        turn_off:
          service: shell_command.light_12


rflink:
  host: 192.168.1.33
  port: 8886

#logger:
#  default: error
#  logs:
#    rflink: debug
#    homeassistant.components.rflink: debug



